#!/usr/bin/env bash
# @file create_taxo_graph
# Create a bash completion script for vke using cli_taxo
# @author Alister Lewis-Bowen <alister@lewis-bowen.org>

[[ -n $DEBUG ]] && set -x
set -eou pipefail

DIR="$PWD"

vke_cli_url() {
    case "$OSTYPE" in
        ## Pulled from `curl https://api.vke.cloud.vmware.com/v1/cli | jq .latest``
        darwin*)  echo 'https://s3-us-west-2.amazonaws.com/cascade-cli-download/pre-prod-us-west-2/latest/mac/vke' ;; 
        linux*)   echo 'https://s3-us-west-2.amazonaws.com/cascade-cli-download/pre-prod-us-west-2/latest/linux64/vke' ;;
        msys*)    echo 'https://s3-us-west-2.amazonaws.com/cascade-cli-download/pre-prod-us-west-2/latest/windows64/vke.exe' ;;
        *)        return 1;;
    esac
    return 0
}

install_vke_cli() {
    echo
    echo "Installing vke CLI... "
    curl "$(vke_cli_url)" > ./vke && chmod 755 ./vke
    return 0
}

install_cli_taxo() {
    echo
    echo "Installing cli_taxo... "
    curl -O https://raw.githubusercontent.com/ali5ter/cli_taxo/master/cli_taxo.py
    curl -O https://raw.githubusercontent.com/ali5ter/cli_taxo/master/bash_completion.tmpl
    curl -O https://raw.githubusercontent.com/ali5ter/cli_taxo/master/requirements.txt
    pip install --user -r requirements.txt
    chmod 755 cli_taxo.py
    return 0
}

generate_taxo_graph() {
    echo
    echo "Generating csv of taxonomy... "
    ./cli_taxo.py vke \
        --commands-token '^COMMANDS:$' \
        --commands-filter '^\s\s\s\s\s(?!-)(\S[^,\s]+)' \
        --options-token 'OPTIONS:$' \
        --options-filter '^\s\s\s(-\S[^,\s]+)|\s(-\S[^,\s]+)\s\s' \
        -o csv -O > data.csv

    echo "Creating svg diagram of taxo data... "
    curl -O https://raw.githubusercontent.com/ali5ter/cli_taxo/master/exp3/radial_tidy_tree_tmpl.html
    mkdir -p "$DIR/taxonomy"
    data="$DIR/taxonomy/data.csv"
    html="$DIR/taxonomy/index.html"
    # shellcheck disable=SC2002
    # shellcheck disable=SC1004
    cat data.csv | sed 's/,/./g' | sed 's/$/,/' | sed '1i\
id,value\
' > "$data"
    # shellcheck disable=SC2002
    # shellcheck disable=SC2086
    cat radial_tidy_tree_tmpl.html | sed "s/##FILE##/$(basename $data)/g" > "$html"
    return 0
}

cd /tmp || exit 1
install_vke_cli
install_cli_taxo
export PATH="$PATH:."
generate_taxo_graph
cd "$PWD" || exit 1
