version: 2

jobs:
  linter:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            shellcheck --external-sources create_completion
            shellcheck --external-sources vke_bash_completion.sh
            shellcheck --external-sources create_taxo_graph

  build_and_source_completion:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Test generation and sourcing of bash autocompletion script
          command: |
            ./create_completion
            source ./vke_bash_completion.sh

workflows:
  version: 2

  commit-workflow:
    jobs:
      - linter
      - build_and_source_completion:
          requires:
            - linter
