version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            shellcheck --external-sources create_completion
            shellcheck --external-sources vke_bash_completion.sh
  build-job:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master